def na = double.nan;
declare fullrange;
input Percentage = 75;
input ExcludeToday = {"No", default "Yes"};
def istoday=if getday()==getlastday() AND ExcludeToday then 1 else 0;
def dayhigh=if istoday then na else high(period="DAY");
def daylow=if istoday then na else low(period="DAY");
def hh=highestall(dayhigh);
def ll=lowestall(daylow);
def range = hh-ll;
def num=30;
def l1 = if num>1 then hh - range / num * 1 else 0;
def l2 = if num>2 then hh - range / num * 2 else 0;
def l3 = if num>3 then hh - range / num * 3 else 0;
def l4 = if num>4 then hh - range / num * 4 else 0;
def l5 = if num>5 then hh - range / num * 5 else 0;
def l6 = if num>6 then hh - range / num * 6 else 0;
def l7 = if num>7 then hh - range / num * 7 else 0;
def l8 = if num>8 then hh - range / num * 8 else 0;
def l9 = if num>9 then hh - range / num * 9 else 0;
def l10 = if num>10 then hh - range / num * 10 else 0;
def l11 = if num>11 then hh - range / num * 11 else 0;
def l12 = if num>12 then hh - range / num * 12 else 0;
def l13 = if num>13 then hh - range / num * 13 else 0;
def l14 = if num>14 then hh - range / num * 14 else 0;
def l15 = if num>15 then hh - range / num * 15 else 0;
def l16 = if num>16 then hh - range / num * 16 else 0;
def l17 = if num>17 then hh - range / num * 17 else 0;
def l18 = if num>18 then hh - range / num * 18 else 0;
def l19 = if num>19 then hh - range / num * 19 else 0;
def l20 = if num>20 then hh - range / num * 20 else 0;
def l21 = if num>21 then hh - range / num * 21 else 0;
def l22 = if num>22 then hh - range / num * 22 else 0;
def l23 = if num>23 then hh - range / num * 23 else 0;
def l24 = if num>24 then hh - range / num * 24 else 0;
def l25 = if num>25 then hh - range / num * 25 else 0;
def l26 = if num>26 then hh - range / num * 26 else 0;
def l27 = if num>27 then hh - range / num * 27 else 0;
def l28 = if num>28 then hh - range / num * 28 else 0;
def l29 = if num>29 then hh - range / num * 29 else 0;



def z1 = if high >= l1 AND low <= l1 AND !istoday then 1 else 0;
def z2 = if high >= l2 AND low <= l2 AND !istoday then 1 else 0;
def z3 = if high >= l3 AND low <= l3 AND !istoday then 1 else 0;
def z4 = if high >= l4 AND low <= l4 AND !istoday then 1 else 0;
def z5 = if high >= l5 AND low <= l5 AND !istoday then 1 else 0;
def z6 = if high >= l6 AND low <= l6 AND !istoday then 1 else 0;
def z7 = if high >= l7 AND low <= l7 AND !istoday then 1 else 0;
def z8 = if high >= l8 AND low <= l8 AND !istoday then 1 else 0;
def z9 = if high >= l9 AND low <= l9 AND !istoday then 1 else 0;
def z10 = if high >= l10 AND low <= l10 AND !istoday then 1 else 0;
def z11 = if high >= l11 AND low <= l11 AND !istoday then 1 else 0;
def z12 = if high >= l12 AND low <= l12 AND !istoday  then 1 else 0;
def z13 = if high >= l13 AND low <= l13 AND !istoday  then 1 else 0;
def z14 = if high >= l14 AND low <= l14 AND !istoday  then 1 else 0;
def z15 = if high >= l15 AND low <= l15 AND !istoday then 1 else 0;
def z16 = if high >= l16 AND low <= l16 AND !istoday then 1 else 0;
def z17 = if high >= l17 AND low <= l17 AND !istoday then 1 else 0;
def z18 = if high >= l18 AND low <= l18 AND !istoday then 1 else 0;
def z19 = if high >= l19 AND low <= l19 AND !istoday then 1 else 0;
def z20 = if high >= l20 AND low <= l20 AND !istoday then 1 else 0;
def z21 = if high >= l21 AND low <= l21 AND !istoday then 1 else 0;
def z22 = if high >= l22 AND low <= l22 AND !istoday then 1 else 0;
def z23 = if high >= l23 AND low <= l23 AND !istoday then 1 else 0;
def z24 = if high >= l24 AND low <= l24 AND !istoday then 1 else 0;
def z25 = if high >= l25 AND low <= l25 AND !istoday then 1 else 0;
def z26 = if high >= l26 AND low <= l26 AND !istoday then 1 else 0;
def z27 = if high >= l27 AND low <= l27 AND !istoday then 1 else 0;
def z28 = if high >= l28 AND low <= l28 AND !istoday then 1 else 0;
def z29 = if high >= l29 AND low <= l29 AND !istoday then 1 else 0;

def pz1 = highestall(TotalSum(z1));
def pz2 = highestall(TotalSum(z2));
def pz3 = highestall(TotalSum(z3));
def pz4 = highestall(TotalSum(z4));
def pz5 = highestall(TotalSum(z5));
def pz6 = highestall(TotalSum(z6));
def pz7 = highestall(TotalSum(z7));
def pz8 = highestall(TotalSum(z8));
def pz9 = highestall(TotalSum(z9));
def pz10 = highestall(TotalSum(z10));
def pz11 = highestall(TotalSum(z11));
def pz12 = highestall(TotalSum(z12));
def pz13 = highestall(TotalSum(z13));
def pz14 = highestall(TotalSum(z14));
def pz15 = highestall(TotalSum(z15));
def pz16 = highestall(TotalSum(z16));
def pz17 = highestall(TotalSum(z17));
def pz18 = highestall(TotalSum(z18));
def pz19 = highestall(TotalSum(z19));
def pz20 = highestall(TotalSum(z20));
def pz21 = highestall(TotalSum(z21));
def pz22 = highestall(TotalSum(z22));
def pz23 = highestall(TotalSum(z23));
def pz24 = highestall(TotalSum(z24));
def pz25 = highestall(TotalSum(z25));
def pz26 = highestall(TotalSum(z26));
def pz27 = highestall(TotalSum(z27));
def pz28 = highestall(TotalSum(z28));
def pz29 = highestall(TotalSum(z29));

def pzmaxA=max(pz1,max(pz2,max(pz3,max(pz4,pz5))));
def pzmaxB=max(pz6,max(pz7,max(pz8,max(pz9,pz10))));
def pzmaxC=max(pz11,max(pz12,max(pz13,max(pz14,pz15))));
def pzmaxD=max(pz16,max(pz17,max(pz18,pz19)));
def pzmaxE=max(pz20,max(pz21,max(pz22,max(pz23,pz24))));
def pzmaxF=max(pz25,max(pz26,max(pz27,max(pz28,pz29))));
def pzmax=max(pzmaxA,max(pzmaxB,max(pzmaxC,max(pzmaxD,max(pzmaxE,pzmaxF)))));

def x=pzmax*percentage/100;
plot TPO1 = if pz1 >= x then l1 else na;
plot TPO2 = if pz2 >= x then l2 else na;
plot TPO3 = if pz3 >= x then l3 else na;
plot TPO4 = if pz4 >= x then l4 else na;
plot TPO5 = if pz5 >= x then l5 else na;
plot TPO6 = if pz6 >= x then l6 else na;
plot TPO7 = if pz7 >= x then l7 else na;
plot TPO8 = if pz8 >= x then l8 else na;
plot TPO9 = if pz9 >= x then l9 else na;
plot TPO10 = if pz10 >= x then l10 else na;
plot TPO11 = if pz11 >= x then l11 else na;
plot TPO12 = if pz12 >= x then l12 else na;
plot TPO13 = if pz13 >= x then l13 else na;
plot TPO14 = if pz14 >= x then l14 else na;
plot TPO15 = if pz15 >= x then l15 else na;
plot TPO16 = if pz16 >= x then l16 else na;
plot TPO17 = if pz17 >= x then l17 else na;
plot TPO18 = if pz18 >= x then l18 else na;
plot TPO19 = if pz19 >= x then l19 else na;
plot TPO20 = if pz20 >= x then l20 else na;
plot TPO21 = if pz21 >= x then l21 else na;
plot TPO22 = if pz22 >= x then l22 else na;
plot TPO23 = if pz23 >= x then l23 else na;
plot TPO24 = if pz24 >= x then l24 else na;
plot TPO25 = if pz25 >= x then l25 else na;
plot TPO26 = if pz26 >= x then l26 else na;
plot TPO27 = if pz27 >= x then l27 else na;
plot TPO28 = if pz28 >= x then l28 else na;
plot TPO29 = if pz29 >= x then l29 else na;

AddCloud(TPO1, TPO2);
addcloud(TPO2,TPO3);
addcloud(TPO3,TPO4);
addcloud(TPO4,TPO5);
addcloud(TPO5,TPO6);
addcloud(TPO6,TPO7);
addcloud(TPO7,TPO8);
addcloud(TPO8,TPO9);
addcloud(TPO9,TPO10);
addcloud(TPO10,TPO11);
addcloud(TPO11,TPO12);
addcloud(TPO12,TPO13);
addcloud(TPO13,TPO14);
addcloud(TPO14,TPO15);
addcloud(TPO15,TPO16);
addcloud(TPO16,TPO17);
addcloud(TPO17,TPO18);
addcloud(TPO18,TPO19);
addcloud(TPO19,TPO20);
addcloud(TPO20,TPO21);
addcloud(TPO21,TPO22);
addcloud(TPO22,TPO23);
addcloud(TPO23,TPO24);
addcloud(TPO24,TPO25);
addcloud(TPO25,TPO26);
addcloud(TPO26,TPO27);
addcloud(TPO27,TPO28);
addcloud(TPO28,TPO29);

TPO1.assignValueColor(if pz1==pzmax then color.white else color.gray);
TPO2.assignValueColor(if pz2==pzmax then color.white else color.gray);
TPO3.assignValueColor(if pz3==pzmax then color.white else color.gray);
TPO4.assignValueColor(if pz4==pzmax then color.white else color.gray);
TPO5.assignValueColor(if pz5==pzmax then color.white else color.gray);
TPO6.assignValueColor(if pz6==pzmax then color.white else color.gray);
TPO7.assignValueColor(if pz7==pzmax then color.white else color.gray);
TPO8.assignValueColor(if pz8==pzmax then color.white else color.gray);
TPO9.assignValueColor(if pz9==pzmax then color.white else color.gray);
TPO10.assignValueColor(if pz10==pzmax then color.white else color.gray);
TPO11.assignValueColor(if pz11==pzmax then color.white else color.gray);
TPO12.assignValueColor(if pz12==pzmax then color.white else color.gray);
TPO13.assignValueColor(if pz13==pzmax then color.white else color.gray);
TPO14.assignValueColor(if pz14==pzmax then color.white else color.gray);
TPO15.assignValueColor(if pz15==pzmax then color.white else color.gray);
TPO16.assignValueColor(if pz16==pzmax then color.white else color.gray);
TPO17.assignValueColor(if pz17==pzmax then color.white else color.gray);
TPO18.assignValueColor(if pz18==pzmax then color.white else color.gray);
TPO19.assignValueColor(if pz19==pzmax then color.white else color.gray);
TPO20.assignValueColor(if pz20==pzmax then color.white else color.gray);
TPO21.assignValueColor(if pz21==pzmax then color.white else color.gray);
TPO22.assignValueColor(if pz22==pzmax then color.white else color.gray);
TPO23.assignValueColor(if pz23==pzmax then color.white else color.gray);
TPO24.assignValueColor(if pz24==pzmax then color.white else color.gray);
TPO25.assignValueColor(if pz25==pzmax then color.white else color.gray);
TPO26.assignValueColor(if pz26==pzmax then color.white else color.gray);
TPO27.assignValueColor(if pz27==pzmax then color.white else color.gray);
TPO28.assignValueColor(if pz28==pzmax then color.white else color.gray);
TPO29.assignValueColor(if pz29==pzmax then color.white else color.gray);